services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_management
    ports:
      - 5672:5672
      - 15672:15672

  golang:
    container_name: golang
    build:
      context: ./go-project/
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  spring_config:
    container_name: spring-config
    build:
      context: ./spring-config/
      dockerfile: Dockerfile
    ports:
      - 3001:3001

  